language: java
install: true
os: linux
dist: jammy
jdk:
  - openjdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - '$HOME/.gradle/caches/'
    - '$HOME/.gradle/wrapper/'

script:
- test/bin/smoketest || travis_terminate 1
- ./gradlew -is clean check

before_deploy:
  - |
    nvm install --lts \
      && nvm use --lts \
      && npm i -g \
        semantic-release \
        @semantic-release/exec \
        @semantic-release/git \
        @semantic-release/changelog \
        @google/semantic-release-replace-plugin

deploy:
  - provider: script
    script: semantic-release
    on:
      branch: master
